dataset:
  num_workers: 4
  batch_size: 512
  n_mels: 64
  n_ffts: 1024
  hop_len: null
  sr: 44100
  duration: 4000
  n_audio_channels: 1
  shift_pct: 0.4

train:
  epochs: 50
  input_dim: 64
  hidden_dim: 256
  output_dim: 10
  num_layers: 2
  device: cpu
  lr: 1e-3
  seed: 42
  gpu: null
  dropout: 0.25

wandb:
  log_val_each_n_epoch: 1
  log_train_loss_each_n_step: 1
  project: "urban-classification"
  entity: "daryoou_sh"
  name: "bosch"
  notes: ""
  local: "false"
